# Generated by Django 5.0 on 2024-05-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalpackage',
            name='fee',
            field=models.IntegerField(null=True),
        ),
    ]
