# Generated by Django 5.0 on 2024-05-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_doctor'),
        ('doctor', '0005_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ManyToManyField(to='doctor.doctor'),
        ),
    ]
