# Generated by Django 5.0 on 2024-05-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_appointment_doctor_appointment_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
    ]
