# Generated by Django 5.0 on 2024-04-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=250)),
                ('subject', models.CharField(max_length=100)),
                ('massage', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'contact_us',
            },
        ),
    ]
